### ISSUE TITLE
cmp-tabnine will disable other completion

### ISSUE THREAD

**Issue by dcy** [tzachar/cmp-tabnine#10]
When i don't set cmp-tabnine
![20211006141147](https://user-images.githubusercontent.com/1137238/136149862-b0c50c35-5ebd-4a99-9a06-db3049f48c26.jpg)

![20211006140644](https://user-images.githubusercontent.com/1137238/136149381-9e5a5092-2171-46d7-ade7-831012933f90.jpg)

And when i set cmp-tabnine
```shell
require'cmp'.setup {
 sources = {
 	{ name = 'cmp_tabnine' },
 },
}
```
![20211006141043](https://user-images.githubusercontent.com/1137238/136149754-66985811-6ed9-4ff8-9e24-fb26adff789c.jpg)

![20211006140853](https://user-images.githubusercontent.com/1137238/136149538-5adb0c1b-e63d-4c7c-b738-8eb1f6449516.jpg)
The nvim-cmp's not work

**Comment by tzachar** [comment]
Well, you need to add all the other sources....
for example: 
```lua
	sources = {
		{ name = 'cmp_tabnine' },
		{ name = 'buffer' },
		{ name = 'path' },
	},

```
