### ISSUE TITLE
Stop tabnine with a command?

### ISSUE THREAD

**Issue by lordvidex** [tzachar/cmp-tabnine#101]
## Why?
I have recorded high memory usage while using tabnine with neovim and would like to stop it during some programming sessions.

## Current Hack
The only way to currently do this is to comment out the `tabnine` setup function, so that tabnine doesn't get loaded as a plugin in nvim. But, this is very stressful and will require a full restart of the neovim session.

## Fix?
It will be a very good feature addition if tabnine can be stopped with a command, so that only the LSP source can be used.

**Comment by tzachar** [comment]
Right now, the plugin implements an automatic restart policy for the tabnine process.
Any implementation would need to take that into account.
If you are willing to implement it, I would accept such a PR. Make sure to include both a Stop and a Start command.

Cheers
