### ISSUE TITLE
Integrate with official TabNine plugin

### ISSUE THREAD

**Issue by c3n21** [tzachar/cmp-tabnine#103]
TabNine seems to have an official NeoVim plugin written in Lua https://github.com/codota/tabnine-nvim, I would like to ask if it would be in your interest to have this plugin integrated with that one.

The main advantage IMO is that both could share the same executable and you could pretty much ditch the whole install script and put `tabnine-nvim` plugin as dependency, so that this plugin will only provide completion.

**Comment by tzachar** [comment]
No.
The architecture is not compatible, as far as I can tell.
It also does not make sense, as the official plugin is a standalone solution, and this plugin is meant to work only as a completion source inside a different completion platform. 
It would make more sense for the official plugin to use this one as a dependency...
