### ISSUE TITLE
how to show tabnine status in lualine or other statusline

### ISSUE THREAD

**Issue by cxwx** [tzachar/cmp-tabnine#107]
I'd love to show tabnine status like 
https://github.com/Exafunction/codeium.vim?tab=readme-ov-file#show-codeium-status-in-statusline

how can I set it

**Comment by tzachar** [comment]
There currently no such functionality implemented.
I would happily accept such a PR.
which status items you think should be reported?

**Comment by cxwx** [comment]
just like the way 
https://github.com/luozhiya/fittencode.nvim/issues/28
need a function `has_suggestion` to return true or false for condition using in lualine
but I don't know how to do it.

**Comment by hoofcushion** [comment]
![image](https://github.com/tzachar/cmp-tabnine/assets/32760059/1c1df934-92c3-4144-ad87-2bc0543c1003)
```lua
--- '3/8' - third suggestion out of 8
--- '0' - Codeium returned no suggestions
--- '*' - waiting for Codeium response
vim.api.nvim_call_function("codeium#GetStatusString", {})
```

I dont know much about tabnine, but for lualine, we got this:

```lua
local isnt_ready={["0"]=true,["*"]=true}
require("lualine").setup({sections={
 lualine_x={                                                   
  function() return "AI" end,                        
  cond=function()
   return not isnt_ready[vim.api.nvim_call_function("codeium#GetStatusString", {})]
  end,
  color={fg="#37b0e7",bg="#101945"},                 
 },                                                  
}})
local section={
}
```

**Comment by cxwx** [comment]
@tzachar  thanks for answer.
Do you know how to set lualine with [codeium.nvim](https://github.com/Exafunction/codeium.nvim) not `codeium.vim`.
Or could I set some lualine from counting each kind of completer?
like [codeium 3 completer, TabNine 3 completer,, ]

**Comment by hoofcushion** [comment]
I think you should ask the maintainer of codeium.nvim for where is the api to get status.

**Comment by tzachar** [comment]
I don't really understand the usability and workflow, as TabNine always have suggestions...
If you need to support a status, you should think which states you want to report. 
I would suggest something like the following:
1) indicate whether TabNine is running or not
2) if running, report the last number of seggestions

Makes sense? Anything else you think should appear?

**Comment by cxwx** [comment]
I thought the solution could be unified to set in `nvim-cmp`
as I could use
`require("cmp").get_entries()`
```
if value.completion_item.cmp.kind_text == "TabNine" then
return true
```
thanks for help
