### ISSUE TITLE
Debug logs & pro api token?

### ISSUE THREAD

**Issue by ThePrimeagen** [tzachar/cmp-tabnine#12]
I have been trying to get this to work for a bit and I seem unable to.  Is there a nice way to debug what's happening (I am getting no tabnine completion).

Also, what is the way to use the pro api token?  I have read through the source and the term token, Token, TOKEN, do not seem to exist.  Not sure where to go with it :) (And its not mentioned in the config.lua source code where I thought it would be).

**Comment by zhongjis** [comment]
@tzachar Not sure if I'm missing something here, but do you mind elaborate where to input this `TabNine::config` command? I tried in editor command with `:` but looks like it doesn't work this way lol
![Screen Shot 2021-11-19 at 11 01 28](https://user-images.githubusercontent.com/23202735/142669905-32ef03b4-9938-4b97-96d0-64930b076410.png)

**Comment by tzachar** [comment]
Just open a new buffer, and type `TAbNine::config` inside neovim.
A tab in your browser should pop up.

**Comment by zhongjis** [comment]
> Just open a new buffer, and type `TabNine::config` inside neovim. A tab in your browser should pop up.

Thank you it worked XD Just in case if there's any other newbie like me trying to figure this out. What I did basically just open a new buffer -> `i` (insert mode) -> type `TabNine::Config`. Then boom, the tab is opened (tbh I never thought it would work like this lol) 

The following pic is the message I see in nvim
![Screen Shot 2021-11-19 at 16 23 14](https://user-images.githubusercontent.com/23202735/142703416-0acc731b-f2cb-4721-8f1c-842c4ae1c4f9.png)
