### ISSUE TITLE
Tabnine doesn't work on windows

### ISSUE THREAD

**Issue by Binx-Codes** [tzachar/cmp-tabnine#13]
I'm using windows, not WSL. I'm basically trying to install tabnine through this plugin. This is what I have in my plugins.lua file:
```lua
use { 'tzachar/cmp-tabnine', run='./install.sh', requires = 'hrsh7th/nvim-cmp' }
```

But I get this whenever I open a file:

![image](https://user-images.githubusercontent.com/68950943/139238454-9a9d4948-1bda-4a36-a9f6-f0296f4d4bee.png)

Is there any solution to this?

**Comment by EtiamNullam** [comment]
I think this issue should be kept open as its still valid.

**Comment by tzachar** [comment]
I don't think its an issue. 
Feel free to open a pull request though.

**Comment by EtiamNullam** [comment]
Don't get me wrong. I know its your repo and your rules but I think nobody that wants to contribute will be looking through closed issues. For sure majority consider closed issues as fixed, impossible or rejected. Its still a problem for many users and its potentially possible to fix it so why not leave it open?

**Comment by tzachar** [comment]
Its very easy to fix, if you have a working Windows setup. I don't.... 
Feel free to submit a PR.

**Comment by EtiamNullam** [comment]
For anyone interested the install script for windows of `tabnine` source for `deoplete` can be of some use:

https://github.com/tbodt/deoplete-tabnine/blob/master/install.ps1
