### ISSUE TITLE
Error while trying to install cmp-tabnine

### ISSUE THREAD

**Issue by vzytoi** [tzachar/cmp-tabnine#16]
Hey, I tried to install this plugin but when I open vim, I have this error : `cmp-tabnine: Cannot find installed TabNine. Please run install.sh` So I executed install.sh this way : `bash install.sh` and I have this error : 
```
install.sh: line 2: $'\r': command not found
: invalid option nameet: errexit
: invalid option nameet: pipefail
: invalid option 7: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
install.sh: line 8: $'\r': command not found
install.sh: line 9: curl: command not found
install.sh: line 10: $'\r': command not found
install.sh: line 11: syntax error near unexpected token `$'in\r''
'nstall.sh: line 11: `case $(uname -s) in
```
I am on Windows 10. Thank you and have a good day

**Comment by adrianiy** [comment]
After some research I've managed to make it work in w11 🥳 

I have a [forked version](https://github.com/adrianiy/cmp-tabnine) with the fix, it is not ready for a PR yet, as for now it only allows x64 versions and I'm setting the version in path manually 😛 . 

But maybe you can give it a try

```
Plug 'adrianiy/cmp-tabnine', { 'do': './install.sh' }
```

ℹ️ What i've done - FYI



- Modified `install.sh` to download windows binaries
- Modified `source.lua`  [binaries method](https://github.com/tzachar/cmp-tabnine/blob/f788bb17e1de13b49e197b68edb501010b64e975/lua/cmp_tabnine/source.lua#L56-L89)
  - fix version to latest version as the regex does not seems to work in windows :s  
  - Use x64 path variable as vim is returning x32 even for these cases
  - Add extension variable to append `.exe` in the binary's path
  
Maybe someone with more knowledge of lua can get to a better solution 😄

**Comment by tzachar** [comment]
Are you trying this on a native Windows nvim? Or inside WSL?

**Comment by adrianiy** [comment]
Native Windows

**Comment by tzachar** [comment]
If your are up to it, take a look at https://github.com/tbodt/deoplete-tabnine/blob/master/install.ps1

Its a Powershell script for installing TabNine.
If you can adjust it to work with this repo, and prepare a pull request, that would be awesome.

**Comment by vzytoi** [comment]
> I have a [forked version](https://github.com/adrianiy/cmp-tabnine) with the fix, it is not ready for a PR yet, as for now it only allows x64 versions and I'm setting the version in path manually 😛 .

I tried and this perfectly  solved my issue, `install.sh` have correctly been installed when I restarted nvim. tysm and have a nice day

**Comment by xanderjakeq** [comment]
ran into this problem. I was trying to install it on Native Windows and tried running the `install.ps1` script manually. I got an [execution policy](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3) error, essentially to protect you from malicious scripts.

Got it working by changing the execution policy: `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`
