### ISSUE TITLE
-apple-darwin/TabNine is not executable

### ISSUE THREAD

**Issue by tomesm** [tzachar/cmp-tabnine#22]
Hello,

I have just encountered the following error after installing the plugin via Plug.

My config:

```
NVIM v0.6.0-dev+631-g72d62aa6a

mac osx 12.01

iterm build 3.4.12
```

Error message:

```
Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: '/Users/martin/.loc
al/share/nvim/plugged/cmp-tabnine/binaries/4.0.9/-apple-darwin/TabNine' is not executable
```

I suspect there is a bug in creating the path to the binary. In my system, the following folder with binaries was created:

```
/.local/share/nvim/plugged/cmp-tabnine/binaries/4.0.9/x86_64-apple-darwin/
```

but the plugin is looking for:
```
/.local/share/nvim/plugged/cmp-tabnine/binaries/4.0.9/-apple-darwin/
```
So the workaround is simply rename
```
/x86_64-apple-darwin/
```
to
```
/-apple-darwin/
```

and the plugin is working after that. But I recommend to try lookup the bug.

I was looking into soruce [file](https://github.com/tzachar/cmp-tabnine/blob/main/lua/cmp_tabnine/source.lua) lines 74 and 84 and it seems looking fine to me.

The _uname_ command is giving me correctly:

```
uname -m
x86_64
```
I dunno where the bug could be (if there is any). I suggest to investigate.

**Comment by tzachar** [comment]
What is the output of this:
```viml
:lua print(vim.fn.has('mac'))
```

**Comment by tomesm** [comment]
Hi,

from
```
:lua print(vim.fn.has('mac'))
1
```

```
:lua print(string.gsub(vim.fn.system('uname -m'), '\n$', ''))
x86_64 1
```

But very strange happens. After been using nvim for several hours suddenly, the plugin started to look up the binary in the correct (initially crated /x86_64-apple-darwin/) folder and I got message:
```
Error executing vim.schedule lua callback: Vim:E475: Invalid value for argument cmd: '/Users/martin/.loc
al/share/nvim/plugged/cmp-tabnine/binaries/4.0.9/x86_64-apple-darwin/TabNine' is not executable
```
So I had to rename `/-apple-darwin/` folder back to `/x86_64-apple-darwin/` and it is working again.

**Comment by tzachar** [comment]
This is very strange.
The code checks for `vim.fn.has('mac')`, and if so the executable is assumed to be 
```
string.gsub(vim.fn.system('uname -m'), '\n$', '') .. '-apple-darwin'
```

Very strange indeed. Wonder why `vim.fn.system('uname -m')` returned an empty string.

**Comment by tzachar** [comment]
Is this still relevant?

**Comment by tomesm** [comment]
Well, its still working so I think you can close it. But unanswered questions remain :)
