### ISSUE TITLE
Invalid value for argument cmd: is not executable

### ISSUE THREAD

**Issue by SingularisArt** [tzachar/cmp-tabnine#23]
Hello all.

I'm really interested in using this plugin, but when I ran `./install.sh`, I get this error message:

```bash
++ curl -sS https://update.tabnine.com/bundles/version
curl: (6) Could not result host: update.tabnine.com
+ version=
```

Can someone please help me?

**Comment by tzachar** [comment]
Looks like you have a dns problem.
What do you get when you try the following:
```
> dig update.tabnine.com
```

**Comment by SingularisArt** [comment]
I just re-did it, and it worked. But, I'm having some trouble setting it up. [Here's](https://github.com/SingularisArt/Death.NeoVim/blob/master/lua/plugin-configs/nv-cmp/init.lua) my cmp config. I don't know what to do.

**Comment by tzachar** [comment]
The name of the source is wrong
Shoukd be cmp_tabnine not tn.
