### ISSUE TITLE
Missing configuration options in `tabnine::config`

### ISSUE THREAD

**Issue by mystilleef** [tzachar/cmp-tabnine#25]
Do you know why there are missing configuration options in `tabnine::config` when using `nvim` as opposed to say `vscode`? I no longer see options like `multiline suggestions` or  `inline completions` when using `nvim`. I remember being able to use `multiline suggestions` with the older `compe-tabnine`. Now this is no longer possible.

**Comment by tzachar** [comment]
No idea.
Try changing the client parameter for tabnine, see if it make a difference.
Otherwise, open an issue with tabnine....
