### ISSUE TITLE
Allow whitelisting languages

### ISSUE THREAD

**Issue by Melkster** [tzachar/cmp-tabnine#26]
Currently the configuration allows settting `ignored_file_types`. Is it possible to allow a whitelist (could for instance be called `allowed_file_types`) of languages for which tabnine is only enabled for, and disabled for all other languages?

**Comment by tzachar** [comment]
This would be unelegant. Having both an allow list and a disallowed list is ungainly.

I think a better option would probably be to change it to a callback, such that each user can implement what works for him.

**Comment by Melkster** [comment]
I personally don't agree that having a whitelist and a blacklist is unelegant, but I adding a callback is fine with me too :)

**Comment by tzachar** [comment]
Having both, the logic gets comicates fairly quickly. Also, documenting the
order of preference between the lists would confound new users.

**Comment by tzachar** [comment]
Take a look at [this](https://github.com/hrsh7th/nvim-cmp#sources-type-tablecmpsourceconfig).
You can set up a per buffer configuration, based on anything you want. This is supported upstream.

I think I will also remove the blacklist.

**Comment by Melkster** [comment]
@tzachar Thanks, that worked for me!
