### ISSUE TITLE
Errors frequently as of recent

### ISSUE THREAD

**Issue by ThePrimeagen** [tzachar/cmp-tabnine#28]
NeoVim Version: 
```
NVIM v0.7.0-dev+653-g7229afcd6
Build type: Debug
LuaJIT 2.1.0-beta3
```

Error: 
```
Error detected while processing TextChangedI Autocommands for "*":
E5108: Error executing lua Vim:E900: Invalid channel id
stack traceback:
        [C]: in function 'chansend'
        ...lson/.vim/plugged/cmp-tabnine/lua/cmp_tabnine/source.lua:154: in function '_do_complete'
        ...lson/.vim/plugged/cmp-tabnine/lua/cmp_tabnine/source.lua:164: in function 'complete'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/source.lua:290: in function 'complete'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/core.lua:246: in function 'complete'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/core.lua:164: in function 'callback'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/core.lua:214: in function 'autoindent'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/core.lua:156: in function 'on_change'
        /home/mpaulson/.vim/plugged/nvim-cmp/lua/cmp/init.lua:302: in function 'callback'
        ...mpaulson/.vim/plugged/nvim-cmp/lua/cmp/utils/autocmd.lua:31: in function 'emit'
        [string ":lua"]:1: in main chunk
```

I see this error get spammed every now and then.  Effectively it wont happen for 5 minutes, then i'll get the error 15 times in a row.  Love tabnine though :).  Thanks for the plugin too.

**Comment by tzachar** [comment]
Looks like the TabNine process dies on you.
Can you try the following patch?
```diff
diff --git a/lua/cmp_tabnine/source.lua b/lua/cmp_tabnine/source.lua
index 51e400c..4f8f63c 100644
--- a/lua/cmp_tabnine/source.lua
+++ b/lua/cmp_tabnine/source.lua
@@ -151,7 +151,10 @@ Source._do_complete = function(ctx)
        }

        table.insert(Source.ctx_list, ctx)
-   fn.chansend(Source.job, fn.json_encode(req) .. "\n")
+ -- fn.chansend(Source.job, fn.json_encode(req) .. "\n")
+ -- if there is an error, e.g., the channel is dead, we expect on_exit will be
+-- called in the future and restart the server
+ pcall(fn.chansend, Source.job, fn.json_encode(req) .. "\n")
 end

 --- complete
```
This will paper over the error messages, but you should still try to understand why TabNine dies. Try to inspect the log file.

**Comment by j-ilden** [comment]
This is something I had a lot yesterday on Windows. Trying to get it up and running on MacOS today. 

First dismissed it and blamed it on the issue of my Windows installations, but if Prime has it as well, then it's worth checking out.

@ThePrimeagen  do you have \* bound to a search? My tabnine wouldn't wanna even work at the beginning. 

These were my culprits:

`" Search for selected text, forwards or backwards.
vim.cmd[[vnoremap <silent> * :<C-U>
  \let old_reg=getreg('"')<Bar>let old_regtype=getregtype('"')<CR>
  \gvy/<C-R><C-R>=substitute(
  \escape(@", '/\.*$^~['), '\_s\+', '\\_s\\+', 'g')<CR><CR>
  \gV:call setreg('"', old_reg, old_regtype)<CR>]]

**Comment by tzachar** [comment]
Adding this to my config on Linux has no effect on TabNine.
I dont see why it should.

**Comment by tzachar** [comment]
Closing this as it is stale.
