### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by Q-Xue** [tzachar/cmp-tabnine#30]
My setting is as below. First part is copied from nvim-cmp configuration. Following part is copied from cmp-tabnine configuration. The source setting overwrites the one in the first part. I tried with a python file. It does not show tabnine results, actually it shows nothing since I overwrite the nvim-cmp source item. However, if I do not overwrite, the cmp configuration works in the same python file. I can see LSP source results. Could you help me to find where I did wrong? I have run the hook script and the folder binaries\4.0.23\x86_64-pc-windows-gnu is generated with 4 exe binaries.

set completeopt=menu,menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
        -- require'snippy'.expand_snippet(args.body) -- For `snippy` users.
      end,
    },
    mapping = {
      ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
      ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
      ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
      ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
      ['<C-e>'] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
      }),
      -- Accept currently selected item. If none selected, `select` first item.
      -- Set `select` to `false` to only confirm explicitly selected items.
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
    },
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' }, -- For vsnip users.
      -- { name = 'luasnip' }, -- For luasnip users.
      -- { name = 'ultisnips' }, -- For ultisnips users.
      -- { name = 'snippy' }, -- For snippy users.
    }, {
      { name = 'buffer' },
    })
  })

  -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline('/', {
    sources = {
      { name = 'buffer' }
    }
  })

  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

  -- Setup lspconfig.
--  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
--  require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
--    capabilities = capabilities
--  }

local lspkind = require('lspkind')

local source_mapping = {
	buffer = "[Buffer]",
	nvim_lsp = "[LSP]",
	nvim_lua = "[Lua]",
	cmp_tabnine = "[TN]",
	path = "[Path]",
}

require'cmp'.setup {
	sources = {
		{ name = 'cmp_tabnine' },
	},
	formatting = {
		format = function(entry, vim_item)
			vim_item.kind = lspkind.presets.default[vim_item.kind]
			local menu = source_mapping[entry.source.name]
			if entry.source.name == 'cmp_tabnine' then
				if entry.completion_item.data ~= nil and entry.completion_item.data.detail ~= nil then
					menu = entry.completion_item.data.detail .. ' ' .. menu
				end
				vim_item.kind = ''
			end
			vim_item.menu = menu
			return vim_item
		end
	},
}

EOF

**Comment by tzachar** [comment]
You should not specify the sources twice. Do so in a single call:
```lua
  sources = cmp.config.sources({                            
    { name = 'cmp_tabnine' },            
    { name = 'vsnip' },                  
    { name = 'nvim_lsp' },               
    { name = 'nvim_lua' },               
    -- { name = 'treesitter' },          
    -- { name = 'buffer' },              
    -- { name = 'path' },                
    { name = 'emoji' },                  
    { name = 'calc' },                   
    { name = 'fuzzy_path'},              
  }),                                    
```

**Comment by Q-Xue** [comment]
I did it in a single call as below. Still not working.




set completeopt=menu,menuone,noselect

lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

local lspkind = require('lspkind')

local source_mapping = {
	buffer = "[Buffer]",
	nvim_lsp = "[LSP]",
	nvim_lua = "[Lua]",
	cmp_tabnine = "[TN]",
	path = "[Path]",
}


local tabnine = require('cmp_tabnine.config')
tabnine:setup({
	max_lines = 1000;
	max_num_results = 20;
	sort = true;
	run_on_every_keystroke = true;
	snippet_placeholder = '..';
	ignored_file_types = { -- default is not to ignore
		-- uncomment to ignore in lua:
		-- lua = true
	};
})

  cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
        -- require'snippy'.expand_snippet(args.body) -- For `snippy` users.
      end,
    },
    mapping = {
      ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
      ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
      ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
      ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
      ['<C-e>'] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
      }),
      -- Accept currently selected item. If none selected, `select` first item.
      -- Set `select` to `false` to only confirm explicitly selected items.
      ['<CR>'] = cmp.mapping.confirm({ select = true }),
    },
    sources = cmp.config.sources({                            
    { name = 'cmp_tabnine' },            
    { name = 'vsnip' },                  
    { name = 'nvim_lsp' },               
    { name = 'nvim_lua' },               
    -- { name = 'treesitter' },          
    -- { name = 'buffer' },              
    -- { name = 'path' },                
    { name = 'emoji' },                  
    { name = 'calc' },                   
    { name = 'fuzzy_path'},              
  }),                          
   
    formatting = {
		    format = function(entry, vim_item)
			    vim_item.kind = lspkind.presets.default[vim_item.kind]
			      local menu = source_mapping[entry.source.name]
			      if entry.source.name == 'cmp_tabnine' then
				    if entry.completion_item.data ~= nil and entry.completion_item.data.detail ~= nil then
					      menu = entry.completion_item.data.detail .. ' ' .. menu
				      end
				      vim_item.kind = ''
			        end
			      vim_item.menu = menu
			          return vim_item
		            end
	          },
  })

  -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline('/', {
    sources = {
      { name = 'buffer' }
    }
  })

  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

  -- Setup lspconfig.
--  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
--  require('lspconfig')['<YOUR_LSP_SERVER>'].setup {
   -- capabilities = capabilities
--  }




EOF

**Comment by tzachar** [comment]
When you open neovim, do you see the tabnine process in the task manager?

**Comment by Q-Xue** [comment]
C:\Users\eidan\AppData\Local\nvim\pack\packager\start\cmp-tabnine\binaries\4.0.23\x86_64-pc-windows-gnu

4 exe binaries in this folder

**Comment by tzachar** [comment]
yes. This might be related to other windows issues.
Im trying to set up a working windows setup. Hopefully this problem would be solved with the rest.

**Comment by tzachar** [comment]
can you try this patch?
```diff
diff --git a/lua/cmp_tabnine/source.lua b/lua/cmp_tabnine/source.lua
old mode 100644
new mode 100755
index 51e400c..3ceec5d
--- a/lua/cmp_tabnine/source.lua
+++ b/lua/cmp_tabnine/source.lua
@@ -17,8 +17,12 @@ local function json_decode(data)
        end
 end

+local function is_win()
+  return fn.has('win64') == 1 or fn.has('win32') == 1
+end
+
 local function get_path_separator()
-    if ((fn.has('win64') == 1) or (fn.has('win32') == 1)) then return '\\' end
+    if is_win() then return '\\' end
     return '/'
 end

@@ -36,8 +40,11 @@ local function build_snippet(prefix, placeholder, suffix, add_final_tabstop)
 end

 local function script_path()
-   local str = debug.getinfo(2, "S").source:sub(2)
-   return str:match("(.*" .. get_path_separator() .. ")")
+  local str = debug.getinfo(2, "S").source:sub(2)
+  if is_win() then
+    str = str:gsub("/", "\\")
+  end
+  return str:match("(.*" .. get_path_separator() .. ")")
 end

 local function get_parent_dir(path)
```

**Comment by vzytoi** [comment]
@Q-Xue while waiting for my PR to be merge, try to use my [fork](https://github.com/vzytoi/cmp-tabnine)
Then go to cmp-tabnine path which should be something like `~/appdata/local/nvim-data/site/pack/packer/start/cmp-tabnine` and run `powershell ./install.ps1` then restart neovim and everything should work just fine

**Comment by tzachar** [comment]
Fixedby #31

**Comment by Q-Xue** [comment]
Thanks a lot!
