### ISSUE TITLE
Module 'cmp_tabnine.config' not found on Windows

### ISSUE THREAD

**Issue by j-ilden** [tzachar/cmp-tabnine#32]
I am creating this for the possible followers of Chris@Machine's Neovim from scratch. This will definitely happen to those who follow his guide and config. 

Related to https://github.com/tzachar/cmp-tabnine/issues/11 but this time on **Windows 10** after fixing #24 #31 #30 README was not updated.

On windows,  plugin cannot be loaded and lazy-loader ([impatient.vim](https://github.com/lewis6991/impatient.nvim)) throws the following error ()
:

E5113: Error while calling lua chunk: ...ck\packer\start\impatient.nvim\lua\impatient\profile.lua:146: ...ck\packer\start\impatient.nvim\lua\impatient\profile.lua:146: module 'cmp_tabnine.config' not found:
        no field package.preload['cmp_tabnine.config']No cache entry
        no file 'C:\Users\myusername\scoop\apps\lua\current'
        no file 'C:\Usersmyusername\scoop\apps\lua\current'
        no file 'C:\Users\myusername\scoop\apps\lua\current'
stack traceback:
        [C]: in function 'error'
        ...ck\packer\start\impatient.nvim\lua\impatient\profile.lua:146: in function 'require'
        C:\Users\myusername\AppData\Local\nvim\init.lua:22: in main chunk

**Comment by j-ilden** [comment]
https://github.com/tzachar/cmp-tabnine/pull/33

**Comment by tzachar** [comment]
Fixed in #33
