### ISSUE TITLE
How to disable tabnine in Telescope?

### ISSUE THREAD

**Issue by AGou-ops** [tzachar/cmp-tabnine#44]
![image](https://user-images.githubusercontent.com/57939102/167582590-a595ec6c-d0f3-463f-aec6-39dca8ed74f3.png)

my config:
```lua
local tabnine = require('cmp_tabnine.config')
tabnine:setup({
    max_lines = 1000;
    max_num_results = 20;
    sort = true;
    run_on_every_keystroke = true;
    snippet_placeholder = '..';
    ignored_file_types = { -- default is not to ignore
    "TelescopePrompt",          -- not working.

    };
})
```

**Comment by AGou-ops** [comment]
iam a fool.

**Comment by tzachar** [comment]
Don't think you are.
Anyway, if someone looks at this issue in the future, this should be disabled inside `cmp`'s configuration.
I am also thinking about removing the `ignored_file_types` option, as it duplicated `cmp`'s functionality.

**Comment by AGou-ops** [comment]
Thank you for your reply!!

I don't know when I removed the comment from this place, so I just wrote it myself.😂
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/57939102/167612207-a3826612-74db-4d63-87de-3edc2f260d07.png">

I just put `TelescopePrompt = true,` in the `ignored_file_types` block, and it works.

**Comment by tzachar** [comment]
Yeah, but you can also use the same config in cmp itself to disable it completely in telescope's prompt
