### ISSUE TITLE
How to install in NvChad?

### ISSUE THREAD

**Issue by HarleyQuinn-Z6** [tzachar/cmp-tabnine#47]
I can't figure out how to install this on NvChad perhaps someone who has the same problem can help me? This is what I've done:
```lua
-- NvChad/lua/custom/plugins/init.lua
return {
   ["tzachar/cmp-tabnine"] = {
      after = "cmp-path",
      config = function()
         require "custom.plugins.tabnine"
      end,
   },
}

-- NvChad/lua/custom/plugins/tabnine.lua
require('cmp_tabnine.config').setup({
   max_lines = 1000;
   max_num_results = 20;
   sort = true;
   run_on_every_keystroke = true;
   snippet_placeholder = '..';
   ignored_file_types = { -- default is not to ignore
           -- uncomment to ignore in lua:
           -- lua = true
   };
   show_prediction_strength = false;
})

-- NvChad/lua/custom/chardrc.lua
M.plugins = {
   override = {
      ["hrsh7th/nvim-cmp"] = {
         sources = {
            { name = "nvim_lsp" },
            { name = "luasnip" },
            { name = "buffer" },
            { name = "nvim_lua" },
            { name = "path" },
            { name = "cmp-tabnine" },
          },
      }
   }
}
```

**Comment by tzachar** [comment]
Never used NvChad. But one issue that comes to mind is that you need to run the install.sh script. 
No Idea how to do that in NvChad. 
You can also call the install.sh script by hand once, which will solve the issue.

**Comment by shanestillwell** [comment]
FWIW. This is how I got TabNine working in NvChad

custom/plugins/init.lua
```
return {
  ["tzachar/cmp-tabnine"] = {
    after = "nvim-cmp",
    run = "./install.sh",
    config = function()
      require "custom.plugins.configs.tabnine"
    end,
  },
}
```

custom/plugins/configs/tabnine.lua
```
local present, cmp = pcall(require, "nvim-cmp")

if not present then
   return
end

local sources = {
  { name = 'cmp_tabnine' },
}

cmp.setup {
   sources = sources,
}

local tabnine = require('cmp_tabnine.config')

tabnine.setup({
	max_lines = 1000,
	max_num_results = 20,
	sort = true,
	run_on_every_keystroke = true,
	snippet_placeholder = '..',
	ignored_file_types = {
		-- default is not to ignore
		-- uncomment to ignore in lua:
		-- lua = true
	},
	show_prediction_strength = true
})
```

**Comment by JasonDorn** [comment]
My setup appears to not be able to hook into tabnine at all.
![image](https://user-images.githubusercontent.com/1330839/201781409-955ca69d-9f9d-4d5f-8894-ee85ccee9680.png)
When I run: :CmpStatus I can see that it's ready

When I run: LspInfo i get:
![image](https://user-images.githubusercontent.com/1330839/201781498-e73acf55-a9e1-47d9-b357-8f27b3f24d89.png)


But when I check Packer:
![image](https://user-images.githubusercontent.com/1330839/201781575-9519b9b4-3bb7-4d7f-b2d3-48387173d02b.png)

I can see it's installed properly.

Does anyone know how I can get cmp to load my tab nine data?

Even my Tabnine hub seems to be picking up my sources and everything

**Comment by tzachar** [comment]
Did you add cmp_tabnine to cmp's sources list?

**Comment by tzachar** [comment]
I don't know why you keep bringing up LSP. TabNine does not interface into any LSP, but operates on its own.
This plugin only plugs TabNine into cmp. 
You need to remove all LSP config which references tabnine.
Anyway, I was asking if you added `cmp_tabnine` as a source for cmp

**Comment by JasonDorn** [comment]
Sorry, newer to these configs, trying to make sense of it all.

I did!
```
  sources = {
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "buffer" },
    { name = "nvim_lua" },
    { name = "path" },
    { name = "cmp_tabnine"}
  },
```

**Comment by tzachar** [comment]
Again, nvim lsp is not connected to cmp. Its the other way around.
cmp will use nvim_lsp to get completion from the running lsp.

**Comment by ansidev** [comment]
My config for NvChad v2.0

File: `lua/custom/plugins.lua`

```lua
  {
    "tzachar/cmp-tabnine",
    lazy = false,
    dependencies = "hrsh7th/nvim-cmp",
    build = "./install.sh",
    config = function()
      require("cmp").setup {
        sources = {
          { name = 'cmp_tabnine' },
        },
      }
      require('cmp_tabnine.config').setup {
        max_lines = 1000,
        max_num_results = 20,
        sort = true,
        run_on_every_keystroke = true,
        snippet_placeholder = '..',
        show_prediction_strength = false
      }
    end,
  },
```

**Comment by tzachar** [comment]
You should call `setup` with a `:` 
```lua
require('cmp_tabnine.config'):setup
```

**Comment by siduck** [comment]
author of nvchad here. i'd suggest using this as it doesnt load the plugin at startup.
@ansidev 
```lua
{
    "hrsh7th/nvim-cmp",
    opts = {
      sources = {
        { name = "nvim_lsp" },
        { name = "luasnip" },
        { name = "buffer" },
        { name = "nvim_lua" },
        { name = "path" },
        { name = "cmp_tabnine" },
      },
    },

    dependencies = {
      {
        "tzachar/cmp-tabnine",
        build = "./install.sh",
        config = function()
          local tabnine = require "cmp_tabnine.config"
          tabnine:setup {} -- put your options here
        end,
      },
    },
},
```
