### ISSUE TITLE
How to open Tabnine Hub on a headless server?

### ISSUE THREAD

**Issue by zhyu** [tzachar/cmp-tabnine#58]
I know run the command `CmpTabnineHub` actually starts an app listens on port 5555, I could use ssh port forwarding to access it. However, I think the hub needs to be accessed via `localhost:5555/a-random-string`, so without knowing the random string, the webapp doesn't load.

Could `cmp-tabnine` get response from tabnine server and print the connection string after running `CmpTabnineHub`?

**Comment by tzachar** [comment]
I don't think TabNine supports this.
As TabNine uses `xdg-open` with the url, you can circumvent the issue by having your own `xdg-open` available in your `PATH` before starting nvim, and logging the arguments sent to it to solve your issue.

**Comment by zhyu** [comment]
Good point about `xdg-open`, I will give it a try later.

Before switching to `nvim-cmp`, I have been using `coc.nvim`. And the extension to `coc.nvim` for Tabnine is https://github.com/neoclide/coc-tabnine, which configures Tabnine via [special commands](https://github.com/neoclide/coc-tabnine#magic-strings). It does tell me the URL I should visit to open the Hub:
![image](https://user-images.githubusercontent.com/1728523/182569432-594bb289-eb62-4b7a-b682-07121f5ccb00.png)

So I think maybe the server responses to the config call with the URL somehow?

**Comment by zhyu** [comment]
So I tried to dump the response from Tabnine after sending the config command to it, and got the following:
```
{
  message = {
    reason = "Couldn't start web browser at http://127.0.0.1:5555/sec-fxdeccwilpzmniggbpdi. See https://tabnine.com/faq#browser_failed"
  },
  status = "Failure"
}
```

Accessing the URL above with ssh port forwarding works as expected.

I think it's possible for the plugin to handle the response and display it.
