### ISSUE TITLE
attempt to index field 'message' (a nil value)

### ISSUE THREAD

**Issue by equal-l2** [tzachar/cmp-tabnine#60]
The plugin stopped working after updating, with the following error message:

```
_tabnine/source.lua:273: attempt to index field 'message' (a nil value)
stack traceback:
^I...pack/packer/start/cmp-tabnine/lua/cmp_tabnine/source.lua:273: in function <...pack/packer/start/cmp-tabnine/lua/cmp_tabnine/source.lua:249>
```

The source line pointed:
https://github.com/tzachar/cmp-tabnine/blob/29402a2786b82b07ffdb118c55c974ab592e4b95/lua/cmp_tabnine/source.lua#L272-L273

**Comment by AGou-ops** [comment]
same here.
