### ISSUE TITLE
CmpTabnineHubUrl   show  an adress with an ephemeral port , though config.json is set to 5555

### ISSUE THREAD

**Issue by allan-simon** [tzachar/cmp-tabnine#68]
i.e I got something like http://127.0.0.1:33271/sec-something

Edit : ok it's because I have two vim process opened 

the weird thing is that this URL will work, while on my first vim, with the URL in 5555, the tabnine hub page is broken (javascript error message in the browser's console) 

Note: I use it inside a docker container if that may provide additional context.

**Comment by tzachar** [comment]
This is the url returned from the process the plugin is connected to.
I don't know if you can override this with tabnine's config. You should contact TabNine's team and ask.

**Comment by allan-simon** [comment]
Isn't because this plugin try to start an instance without checking if one is already running ?

**Comment by tzachar** [comment]
The plugin always starts a new instance.
Support a single instance is out of scope for this plugin.
