### ISSUE TITLE
curl: (60) SSL certificate problem

### ISSUE THREAD

**Issue by ALipAkrohk** [tzachar/cmp-tabnine#71]
Unfortunately, curl cannot download tabnine from your server.

>  ++ curl -sS https://update.tabnine.com/bundles/version
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> More details here: https://curl.se/docs/sslcerts.html
> 
> curl failed to verify the legitimacy of the server and therefore could not
> establish a secure connection to it. To learn more about this situation and
> how to fix it, please visit the web page mentioned above.
> `+ version=`

What way do you suggest to solve this problem?

**Comment by tzachar** [comment]
The download is from TabNine's servers.
There is nothing I can do about ur error.
Try updating you CA files.
