### ISSUE TITLE
Spawning many tabnine processes

### ISSUE THREAD

**Issue by lopi-py** [tzachar/cmp-tabnine#73]
I just have one file open and sometimes I open others but I delete that buffers and then there is one left but tabnine processes seems not killed and causes slowdowns in my entire computer.
![image](https://user-images.githubusercontent.com/70210066/194776022-a02d87fa-b45b-458a-b4f3-64c8cac6a24c.png)
(There are more processes not shown in the screenshot)
btw: when I exit neovim, all process get killed. Also I get this everytime I want to enter the hub: 
![image](https://user-images.githubusercontent.com/70210066/194776247-d6faea95-c1bd-4532-876e-7950f3057913.png)

### Details
os: `Windows`
nvim version: `NVIM v0.9.0-dev-55-gedc8a1f04`
nvim gui: `Neovide 0.10.1`

**Comment by tzachar** [comment]
This plugin opens up a new tabnine process only in the following cases:
1) when starting a new instance of neovim
2) when there was an error communicating with the running tabnine process
Tabnine itself is prone to open new instances, especially when updating to a newer version (tabnine does that itself).

try running with the following patch, and lets see if the plugin is the culprit:
```diff
diff --git a/lua/cmp_tabnine/source.lua b/lua/cmp_tabnine/source.lua                             
index 329b212..2d8cb97 100644                                                                    
--- a/lua/cmp_tabnine/source.lua                                                                 
+++ b/lua/cmp_tabnine/source.lua                                                                 
@@ -270,6 +270,7 @@ function Source.on_exit(self, job, code)                                     
   end                                                                                           
   self.tabnine_version = version                                                                
   self.pending = {}                                                                             
+  dump('starting a new tabnine process. reason:', code)                                         
   self.job = fn.jobstart({ bin, '--client=cmp.vim' }, {                                         
     on_stderr = nil,                                                                            
     on_exit = function (j, c, _) self:on_exit(j, c) end,                                        
```

I would also try to disable the cloud option and see if it helps.

**Comment by lopi-py** [comment]
Thanks, I'll try but I can't disable cloud because of the above capture, I get it everytime I want to access the hub

**Comment by lopi-py** [comment]
I can't reproduce now the multiple instances but I found that at startup, 2 are spawned:
![image](https://user-images.githubusercontent.com/70210066/195718063-f00528aa-48b3-46a5-87f7-e38344742b2d.png)
I guess that only 1 should be spawned.

Also I'm getting delay when typing, but seems related to tabnine maybe? My pc isn't too good, thats I why use cloud but it's weird anyway
![image](https://user-images.githubusercontent.com/70210066/195717951-0c3e3995-1536-4260-8089-4c016ce9c675.png)

**Comment by lopi-py** [comment]
Something like a keystroke debounce may help?

**Comment by tzachar** [comment]
> 



> Something like a keystroke debounce may help?
> 
This can be set in cmp.

> **Edit**: Ok, I noticed that I should use `require("cmp_tabnine.config").setup"` instead of `require("cmp_tabnine").setup`, now one instance is spawned

yes, the second one is internal to cmp. you should use the first option

**Comment by lopi-py** [comment]
Seems more related to tabnine than this plugin, but I still can't access the hub

**Comment by alechp** [comment]
@lopi-py try running `:CmpTabnineHubUrl` and clicking the link. 

Running `CmpTabnineHub` prefixes with Tabnine's actual website, which doesn't work

(Assuming that there was a GET param which used to handle redirect and has since been disabled on Tabnine's end, but just a random guess)

What I see when I run `:CmpTabnineHub`:
![Screen Shot 2022-10-14 at 1 41 30 PM](https://user-images.githubusercontent.com/3058939/195944437-3fc881dd-ad1c-427e-9319-176546c96387.png)

What I see when I run `:CmpTabnineHubUrl` (and click the link that pops up via vim-notify):
![Screen Shot 2022-10-14 at 1 54 07 PM](https://user-images.githubusercontent.com/3058939/195944553-ae64eb4a-3e17-4fd1-ac9b-03337b11986a.png)

![Screen Shot 2022-10-14 at 1 54 12 PM](https://user-images.githubusercontent.com/3058939/195944501-20e06299-d0ad-4630-9781-feedfdc96da9.png)

**Comment by lopi-py** [comment]
@alechp Ah thanks! I'm able to enter the hub, closing this since its related to tabnine

**Comment by alechp** [comment]
@lopi-py Just checked and default link generated by `:CmpTabnineHub` breaks when using Brave. Tested in Firefox and it works fine without the URL workaround

Tabnine docs: https://support.tabnine.com/hc/en-us/articles/9115214579601-Tabnine-hub-is-showing-Lost-conenction-Please-reopen-the-Tabnine-Hub-

What I see in Brave: 
![Screen Shot 2022-10-16 at 1 14 17 PM](https://user-images.githubusercontent.com/3058939/196056111-cfabe44f-8c87-47c7-a5da-019dac450de0.png)

What I see in Firefox:
![Screen Shot 2022-10-16 at 1 13 59 PM](https://user-images.githubusercontent.com/3058939/196056102-c4706e3c-6931-444a-8534-a80b88fe6f01.png)

**Comment by lopi-py** [comment]
@alechp Oh, I was using brave too, I just tried with opera and it works, thanks for the info 😄
