### ISSUE TITLE
Tabnine Hub: Lost Connection

### ISSUE THREAD

**Issue by zeitchef** [tzachar/cmp-tabnine#74]
I'm fairly certain I've gotten everything configured properly and I'm logged into TabNine, but for some reason `:CmpTabnineHub` does not want to connect. `CmpStatus` also lists TabNine as "unused".

Here's my relevant config:

```
cmp.setup {
  experimental = {
    native_menu = false,
    ghost_text = true,
  },
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  mapping = cmp.mapping.preset.insert {
    ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    ['<C-p'] = cmp.mapping.select_prev_item(),
    ['<C-n'] = cmp.mapping.select_next_item(),
    ['<C-e'] = cmp.mapping.close(),
    ['<Shift-Space>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm { select = true },
  },
  formatting = {
    fields = { 'kind', 'abbr', 'menu' },
    format = function(_, vim_item)
      vim_item.menu = vim_item.kind
      vim_item.kind = icons[vim_item.kind]

      return vim_item
    end,
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'luasnip' },
    { name = 'cmp_tabnine' },
    { name = 'buffer' },
    { name = 'path' },
  },
  preselect = cmp.PreselectMode.None,
}

cmp.setup.cmdline('/', {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = 'buffer' },
  },
})

tabnine.setup {
  show_prediction_strength = true,
}
```

Am I overlooking something?

**Comment by zeitchef** [comment]
Service seems to be running, but when I hit the URL in the browser, it appears some verification needs to happen - but this is not my TabNine account. ???

<img width="1112" alt="Screen Shot 2022-10-18 at 16 33 26" src="https://user-images.githubusercontent.com/6670659/196460676-04f2b33c-07e6-424d-bd82-63e88767e5b6.png">

**Comment by tzachar** [comment]
This is not enough information to help you.

**Comment by tzachar** [comment]
How can you tell its another account? Its not apparent from the image above.
Anyway, you need to use this page to login into your own account.

**Comment by zeitchef** [comment]
I'm already logged into Tabnine Hub:

<img width="250" alt="Screen Shot 2022-10-19 at 10 06 01" src="https://user-images.githubusercontent.com/6670659/196633898-3f12965d-7526-407c-884f-19ab231f6d33.png">

The screenshot above is a completely different account (with over 1600) notifications - that is not my account.

**Comment by zeitchef** [comment]
This could have been an anomaly. I just tested and `:CmpTabnineHub` does attach the correct URL as query parameter, but nevertheless the connection fails because it assumes I'm not logged in. When I open the hub directly in the browser, I'm logged in.

**Comment by tzachar** [comment]
I think you are missing something.
Opening the hub of you locally running tabnine process enables you to configure it, and set your account info.
Did you do this?

**Comment by zeitchef** [comment]
Again, I just ran `:CmpTabnineHubUrl` and and opened the URL this returned in my browser - this is not my account.

<img width="1076" alt="Screen Shot 2022-10-19 at 12 59 05" src="https://user-images.githubusercontent.com/6670659/196674231-59df0f14-c374-4f83-a589-fdff503ff598.png">

I have no idea what configuration needs to be done - you mention it in the README but this links to a document header, which is not very clear. For the record, I have logged into the Tabnine Hub so I would expect this to just work, unless you can be clearer on what exact configuration needs to be done.

**Comment by tzachar** [comment]
once you open the hub from within nvim, you should be able to login via the top left menu.
anyway, this should not stop you from getting completions. maybe you disabled the tabnine source for a specific file type?
try giving a minimal working config which recreates the problem.

**Comment by Ben2146053** [comment]
I had the same issue. I was experimenting with Tabnine with a different Nvim plugins something might have got messed up. What helped me was to delete all the contents in the Engine file path, and reinstall this plugin. Mine was found in `/home/.local/share/nvim/site/pack/packer/start/cmp-tabnine` 
If you go to Tabnine Hub -> Support -> General Info you can find where the Engine Path is.

**Comment by jellydn** [comment]
Just FYI - I got into this issue on my PC with Brave. It works after it turns off the shield. Refer https://gyazo.com/67d6bdedeacbc78c30b34141744a9004

**Comment by tzachar** [comment]
Closing this, as it seems to be related to specific browsers.
