### ISSUE TITLE
Config is being ignored?

### ISSUE THREAD

**Issue by chrisgrieser** [tzachar/cmp-tabnine#75]
I copypasted the default config from the readme and any changes in the config are completely ignored.

TabNine is working fine though.

Not sure if this is related, but the first time a completion from tabnine is requested, I get this message
<img width="1031" alt="Pasted image 2022-11-12 14 23 51" src="https://user-images.githubusercontent.com/73286100/201476104-2d34f4e2-f135-468a-b35e-750ca9973aff.png">
<img width="1199" alt="Pasted image 2022-11-12 14 22 16" src="https://user-images.githubusercontent.com/73286100/201476091-4c220efd-5283-445e-9d5d-05fd3b797e07.png">

**Comment by tzachar** [comment]
Please be a bit more specific about what is not working.
And the image above is not related to this plugin but to another.

**Comment by chrisgrieser** [comment]
oh sorry, I assumed that that luassert prompt had something to do with tabnine, since it appeared at the pretty much the same time when I installed cmp_tabnine. Weird coincidence I guess.

Well, it's simply that any change to the config simply has no effect, regardless which one, even after restarting. Here an example:
![image](https://user-images.githubusercontent.com/73286100/201519858-e06ae095-de95-4180-8d8a-94ab31862f31.png)

**Comment by tzachar** [comment]
Please use `:` instead of `.` 
It was a misspelling in the `README`....

**Comment by chrisgrieser** [comment]
ah, yes, that fixed it, thank you!

I think practically every neovim plugin uses `.setup` instead of `:setup`, which might be a bit confusing in the first place, btw.
