### ISSUE TITLE
Missing multiple features on clean install

### ISSUE THREAD

**Issue by PneumaOfficial** [tzachar/cmp-tabnine#80]
I'm using the recommended configuration, but how do I enable multiline suggestions? I've already configured it with the tabnine hub
Also, the dictionary isn't working, 
![image](https://user-images.githubusercontent.com/39502544/205220442-52c97a81-1d1f-4141-bab5-0fa4a4c64524.png)

Here's my configuration:
https://pastebin.com/raw/uzvGBsxY

**Comment by tzachar** [comment]
Multiline suggestions are not consistently working. Its not a problem with this plugin but with tab nine itself. You can look at previous issues where its discussed.

As for the "dictionary is not working" I have no idea what you mean.

**Comment by lightwrath** [comment]
As of the last few days, can confirm that the multi-line completion issue is resolved. Ensure you get the latest version of the engine as shown on the hub and are triggering cmp on a new line. I think the default is Ctrl-space, else check your mappings.
Thank you to all those involved.

**Comment by tzachar** [comment]
Closing this as stale.
