### ISSUE TITLE
cmp-tabnine: Cannot find installed TabNine. Please run install.sh

### ISSUE THREAD

**Issue by alanmicah** [tzachar/cmp-tabnine#81]
When starting nvim I get this _cmp-tabnine: Cannot find installed TabNine. Please run install.sh_

Installing plugins through packer

**Running:**
Nvim: 0.8.0
macOS: 12.6.1
iTerm2: 3.4.16 (this error appears in the default terminal as well)
zsh: 5.8.1

**Comment by tzachar** [comment]
As the message says, try running the install.sh script by hand.
