### ISSUE TITLE
Auto-imports on Tabnine completions

### ISSUE THREAD

**Issue by robmeijerink** [tzachar/cmp-tabnine#82]
I use this plugin when working in neovim on web development (php, js etc.). The suggestions are working great! However, when I select a Tabnine suggestion that requires an import of for example a class. The class is not auto imported at the top of the file.

Cmp with LSP does do these auto imports whenever I select a LSP suggestion.

Is this currently possible with this plugin? I am curious to the status of this feature and I am willing to contribute if someone can point me in the right direction.

**Expected Behavior:**

Whenever I select a Tabnine cmp suggestion which requires an import of a class: The import should be automatically added.

**Actual Behavior:**

Whenever I select a Tabnine cmp suggestion which requires an import of a class: Only the autocomplete works, but it does not import the class.

**Comment by tzachar** [comment]
TabNine is not a language server, and does not implement the language server protocol.
Moreover, TabNine may not even be aware if the import already exists or not, as TabNine only sees a portion of a file at a time.

If you want such functionality, try contacting the tab nine team.
