### ISSUE TITLE
Termux build

### ISSUE THREAD

**Issue by KaiVinter** [tzachar/cmp-tabnine#84]
Hello!

I tried instaling cmp-tabnine in Termux (Android) with Packer on Neovim, but the installation fails. I thought it was an issue with `sudo`, because my device is not rooted and can't use `sudo`, but it doesn't seem to be the case.
For what I understand, it has to install some binaries, but this page doesn't seem to open, and it seems related:

https://update.tabnine.com/bundles/4.4.214/armv8l-unknown-linux-musl/TabNine.zip

If Android is not supported, is there a way to compile it manually for Android, or make a general Android build?

Thank you!

**Comment by tzachar** [comment]
I don't think TabNine supports android.
Try contacting their support directly.
