### ISSUE TITLE
Latest TabNine binary doesnt have executable permissions

### ISSUE THREAD

**Issue by sriramkandukuri** [tzachar/cmp-tabnine#85]
Hi,

With latest update of plugin, I have seen an error saying `<nvim plugins path>/TabNine` is not executable
But executable is present in that folder without executable permissions. please check.

**Comment by tzachar** [comment]
Well, you have your answer right there...
Make sure it is executable.
It is probably a problem with the upstream binary blob, maybe report the bug to the TabNine team?

**Comment by lngsx** [comment]
This is not an issue anymore after `4.4.225`
