### ISSUE TITLE
Problem with multi-line completion preview not receiving all lines or cutting it off

### ISSUE THREAD

**Issue by henryoliver** [tzachar/cmp-tabnine#87]
Something simple to solve, but for some reason, the preview for ML completion is cutting or not receiving more than ten lines. I'm a pro user at Tabnine, and all my configuration seems fine here; my LSP previews go beyond 10 lines:

![image](https://user-images.githubusercontent.com/870784/212416082-845e0834-daa8-4630-b51b-1cbd6db34444.png)

```
tabnine:setup({
    max_lines = 1000,
    max_num_results = 20,
    sort = true,
    run_on_every_keystroke = true,
    snippet_placeholder = " ",
    show_prediction_strength = true,
})
...
                if entry.source.name == "cmp_tabnine" then
                    local detail = (entry.completion_item.data or {}).detail

                    vim_item.kind = " "

                    if detail and detail:find(".*%%.*") then
                        vim_item.kind = vim_item.kind .. " " .. detail
                    end

                    if (entry.completion_item.data or {}).multiline then
                        vim_item.kind = vim_item.kind .. " " .. "[AI  - ML]"
                    end
                end

...
```

I appreciate any help you can give here. Thanks!

**Comment by tzachar** [comment]
I don't think this has something to do with this plugin, as I am not limiting the number of lines in the preview.
It might related to the way you set up `cmp`'s documentation window.
Anyway, you can map keys to scroll the documentation window. Check `cmp`'s config.

**Comment by henryoliver** [comment]
thanks @tzachar , all other documentation windows expand and have scroll on it, the only one with this issue is tabnine. But I'll do some research and try to work on my `cmp` config here. Thanks again!

**Comment by henryoliver** [comment]
@tzachar , the issue is somewhere here on this return, as you can see the value cuts on a certain threshold:

```
...
documentation = {
    kind = "markdown",
    value = '```javascript\nconst parseUrl = (url) => {\n    const link = document.createElement("a");\n    link.href = url;\n    return link;\n};\n\nconst test = Object.create(inserter, {\n    name: {\n        value: "test",\n    },\n```'
  },
  ...
 ```

 https://github.com/tzachar/cmp-tabnine/blob/main/lua/cmp_tabnine/source.lua#L397
 
 Is there a way to put a `log` on this `result` to see if Tabnine is actually sending the whole suggestion or just part of it?

**Comment by tzachar** [comment]
you can use `dump()`.

**Comment by tzachar** [comment]
Anything on this?
