### ISSUE TITLE
Lazy plugin manager

### ISSUE THREAD

**Issue by Pakrohk** [tzachar/cmp-tabnine#90]
How can I use your plugin with the help of lazy.nvim?

I tried to install the plugin in the way that I send below, but I encountered a problem.
```lua
{
"tzachar/cmp-tabnine", cmd = "./install.sh" 
		dependencies = "hrsh7th/nvim-cmp",
}
```

**Comment by Pakrohk** [comment]
The method you wrote in the readme to use lazy should be modified as follows:
```lua
{
	"hrsh7th/nvim-cmp",
	event = "InsertEnter",
	dependencies = {
		{ 
		"tzachar/cmp-tabnine", build = "./install.sh" },
		...
		...
		},
	config = function()
	...
	...
	end,
}
```
https://github.com/Pakrohk-DotFiles/NvPak/blob/main/lua/plugins.lua#%22hrsh7th/nvim-cmp%22

**Comment by tzachar** [comment]
Why?

I see no need to supply instructions on how to enable `cmp` with lazy.

**Comment by Pakrohk** [comment]
> Why?
> I see no need to supply instructions on how to enable cmp with lazy.

If cmp is not activated correctly, tabnine will also not work properly, please note that this is a tabnine plugin for cmp, not an independent tabnine plugin for neovim.

The way you currently write in readme it cannot enable cmp and tabnine properly.
My intention was only to help.

**Comment by tzachar** [comment]
I don't think I should explain how to install `cmp` on this repo.
And I don't see any issues with the current installation instructions; The instructions show exactly how to install _this_ plugin. Installing `cmp` is the plugin user's responsibility, and they should consult `cmp` documentation -- which might change.

**Comment by Pakrohk** [comment]
> I don't think I should explain how to install` cmp` on this repo.
And I don't see any issues with the current installation instructions; The instructions show exactly how to install this plugin. Installing `cmp` is the plugin user's responsibility, and they should consult `cmp` documentation -- which might change.

My friend, this is related to the working method of `lazy.nvim`, `not cmp activation`, you should use `cpm` as a prerequisite in the method you wrote, but `lazy.nvim` does not behave in this way, and this causes problems. 
Please try to activate `tabnine` with the method you wrote, you will see for yourself why I sent this to you.
I think we have talked about it enough.
