### ISSUE TITLE
Tabnine completion items move to the right in nvim-cmp

### ISSUE THREAD

**Issue by ADkun** [tzachar/cmp-tabnine#91]
See issue in https://github.com/hrsh7th/nvim-cmp/issues/1476

Snapshot:
![image](https://user-images.githubusercontent.com/33215032/223626044-f5778f24-1e4c-4f51-86b3-341ad39ca426.png)

**Comment by tzachar** [comment]
First, change `tabnine.setuip` to `tabnine:setup`.
Other than that, try removing the alien icon you are using. It might be a problem with your terminal.
