### ISSUE TITLE
Issue on startup

### ISSUE THREAD

**Issue by katulevskiy** [tzachar/cmp-tabnine#92]
cmp-tabnine: Cannot find installed TabNine. Please run install.sh

I use astronvim with lua config, so there might be errors in the config.
I also install all the plugins using PackerSync.
As for the install.sh, it was created by plugin in directory .vim/plugged/completion-tabnine/install.sh

When I run it, here is the output:
./install.sh
+ rm TabNine
++ curl -sS https://update.tabnine.com/version
+ version=3.2.28
+ case $(uname -s) in
++ uname -s
+ platform=apple-darwin
++ uname -m
+ triple=arm64-apple-darwin
++ dirname ./install.sh
+ cd .
+ path=3.2.28/arm64-apple-darwin/TabNine
+ [[ -f binaries/3.2.28/arm64-apple-darwin/TabNine ]]
++ uname -s
+ [[ -e binaries/TabNine_Darwin ]]
++ uname -s
+ ln -sf 3.2.28/arm64-apple-darwin/TabNine binaries/TabNine_Darwin
+ exit

When I open any file in nvim after that, the error stays in place.

**Comment by katulevskiy** [comment]
[init.lua.zip](https://github.com/tzachar/cmp-tabnine/files/10945979/init.lua.zip)

Here is my init.lua file

**Comment by tzachar** [comment]
You are not using this plugin.
You are using https://github.com/aca/completion-tabnine
Please open an issue there.
