### ISSUE TITLE
Insert value into documentation

### ISSUE THREAD

**Issue by JohnnyMcWeed** [tzachar/cmp-tabnine#95]
When having set the window to a smaller max-width with lsp-kind (e. g. `maxwidth = 40`), this cuts the value and it's not shown anywhere unless ghost_text is used on `hrsh7th/nvim-cmp`.
It would be great if the value could be placed into the documentation window (e. g. with another setting in the configuration) when there is no documentation .

**Comment by tzachar** [comment]
Not sure what is meant by "value" here. 
If you mean the completion text, then this is an issue with core cmp. This plugin has no control over the display of the completion menu, and placing the completion text into the documentation window makes no sense, as cmp-tabnine has no access to the information that you set maxwidth.

**Comment by JohnnyMcWeed** [comment]
Yes, I meant the completion text.
I meant more like a config switch to always show it in the documentation window, if it is not filled.
(The max width setting was meant as an example on when this can be useful.)

**Comment by tzachar** [comment]
This is not specific to this plugin.
I would suggest you try your luck with upstream `cmp`.
Cheers.
